Wish.Picture/Wish.Picture.Web/Models/Picture.cs
namespace Wish.Picture.Web.Models
{
    public class Picture
    {
        public int Id { get; set; }

        public string PictureHash { get; set; }

        public string PictureKey { get; set; }
        public string PictureUrl { get; set; }
        public string PictureName { get; set; }
        public string Creator { get; set; }



    }
}

Wish.Picture/Wish.Picture.Web/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Qiniu.Http;
using Qiniu.IO;
using Qiniu.IO.Model;
using Qiniu.Util;
using Wish.Picture.Web.Helpers;
using Wish.Picture.Web.Models;
using Wish.Picture.Web.Repository;

namespace Wish.Picture.Web.Controllers
{
    public class PictureController : Controller
    {
        public IActionResult Index()
        {
            var loginUserName = HttpContext.Session.GetString("LoginUserName");
            if (!string.IsNullOrEmpty(loginUserName))
            {
                ViewData["loginUserName"] = loginUserName;
            }

            var repository = new PictureRepository();
            var pictureList = repository.GetPictures();
            if (pictureList.Count >= 1)
            {
                ViewData["PictureList"] = pictureList;
            }

            return View();
        }

        [HttpGet]
        public IActionResult Upload()
        {
            var loginUserName = HttpContext.Session.GetString("LoginUserName");
            if (!string.IsNullOrEmpty(loginUserName))
            {
                ViewData["loginUserName"] = loginUserName;
                return View();
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
            
        }

        public IActionResult UploadImg()
        {

            var loginUserName = HttpContext.Session.GetString("LoginUserName");
            if (!string.IsNullOrEmpty(loginUserName))
            {
                IFormFileCollection files = Request.Form.Files;
                //这里的ak sk 可以写到配置文件中方便修改
                Mac mac = new Mac("", "");
                // 上传策略，参见 
                // https://developer.qiniu.com/kodo/manual/put-policy
                PutPolicy putPolicy = new PutPolicy();
                // 如果需要设置为"覆盖"上传(如果云端已有同名文件则覆盖)，请使用 SCOPE = "BUCKET:KEY"
                // putPolicy.Scope = bucket + ":" + saveKey;  
                //上传储存的空间名称
                putPolicy.Scope = "ling-picture";
                // 上传策略有效期(对应于生成的凭证的有效期)          
                putPolicy.SetExpires(3600);
                // 上传到云端多少天后自动删除该文件，如果不设置（即保持默认默认）则不删除
                // putPolicy.DeleteAfterDays = 1;
                string jstr = putPolicy.ToJsonString();
                //获取上传凭证
                var uploadToken = Auth.CreateUploadToken(mac, jstr);

                //false 使用https 自动识别存储空间            
                Qiniu.Common.Config.AutoZone("", "ling-picture", false);

                UploadManager um = new UploadManager();
                foreach (IFormFile file in files)//获取多个文件列表集合
                {
                    if (file.Length > 0)
                    {
                        Stream stream = file.OpenReadStream();
                        //var fileName = ContentDispositionHeaderValue
                        //.Parse(file.ContentDisposition)
                        //.FileName
                        //.Trim('"');
                        string fileName = file.FileName.Substring(file.FileName.LastIndexOf('.')); //文件扩展名
                                                                                                   //DateTime.Now.ToString("yyyyMMddHHmmssffffff")
                        var saveKey = "piture/" + Guid.NewGuid().ToString("N") + fileName;//重命名文件加上时间戳 其中上传地址也可以配置s   
                        var waterMarkerStream = AddWaterMarker(stream, fileName);
                        waterMarkerStream.Seek(0, SeekOrigin.Begin);    //将字节流中的position复位  fix 上传图片为空问题
                        HttpResult result = um.UploadStream(waterMarkerStream, saveKey, uploadToken);

                        if (result.Code == 200)
                        {
                            var res = result.Text.ToObject<UploadResult>();
                            var repository = new PictureRepository();
                            var addRes = repository.SavePictureInfo(res, loginUserName, file.FileName);
                            if (addRes)
                            {
                                return Content("上传成功");
                            }
                            else
                            {
                                return Content("上传失败");
                            }
                        }
                        else
                        {
                            throw new Exception(result.RefText);//上传失败错误信息
                        }
                    }
                }
                return null;
            }
            else
            {
                return RedirectToAction("Login", "User");
            }


            
        }

        private MemoryStream AddWaterMarker(Stream stream,string fileSuffixName)
        {
            var watermarkedStream = new MemoryStream();
            stream.Seek(0, SeekOrigin.Begin);    //修正stream中的position位置
            using (var img = Image.FromStream(stream))
            {
                using (var graphic = Graphics.FromImage(img))
                {
                    var font = new Font("WenQuanYi Zen Hei", 20);
                    var color = Color.FromArgb(128, 255, 0, 126);
                    var brush = new SolidBrush(color);
                    var point = new Point(img.Width - 120, img.Height - 30);
                    graphic.DrawString("木子", font, brush, point);
                    var format = ImageFormat.Png;
                    switch (fileSuffixName.ToLower())
                    {
                        case ".jpg":
                        case ".jpeg": 
                            format = ImageFormat.Jpeg;
                            break;
                        case ".png":
                            format = ImageFormat.Png;
                            break;
                        case ".bmp":
                            format = ImageFormat.Bmp;
                            break;
                        case ".icon":
                            format = ImageFormat.Icon;
                            break;
                    }
                    img.Save(watermarkedStream, format);
                }
            }

            return watermarkedStream;
        }

    }
}

Wish.Picture/Wish.Picture.Web/Views/Picture/Index.cshtml
@{
    ViewData["Title"] = "图片库";
}
<link rel="stylesheet" type="text/css" href="css/normalize.css" />
<link rel="stylesheet" type="text/css" href="css/default.css">
<link rel="stylesheet" href="css/swipebox.css">
<style>
    #box-container {
        margin: 0;
        padding: 0;
    }

    .box {
        list-style-type: none;
        float: left;
        margin-bottom: 1rem;
        margin-left: 1%;
        margin-right: 1%;
        width: 48%;
    }

    .box:nth-child(2n+1) {
        clear: both;
        margin-left: 0;
    }

    .box:nth-child(2n+0) {
        margin-right: 0;
    }

    .box a {
        display: block;
        width: 100%;
        height: auto;
    }

    .box a img {
        -webkit-back-visibility: hidden;
        display: block;
        width: 100%;
        height: auto;
        vertical-align: bottom;
    }
</style>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">标签</div>
        <div class="col-md-8">
            <div class="wrap small-width">
                <div id="try"></div>
                <ul id="box-container">
                    @{
                        var pictureListModel = ViewData["PictureList"];
                        if (pictureListModel != null)
                        {
                            var pictureList = pictureListModel as List<Picture>;

                            foreach (var picture in pictureList)
                            {
                                <li class="box">
                                    <a href="@picture.PictureUrl" class="swipebox" title="@picture.PictureName">
                                        <img src="@picture.PictureUrl" alt="image">
                                    </a>
                                </li>
                            }

                        }
                    }
                </ul>
            </div>
        </div>
        <div class="col-md-2">
            <a asp-controller="Picture" asp-action="Upload">上传图片</a>
        </div> 
    </div>
</div>

<script src="~/js/ios-orientationchange-fix.js"></script>

<script src="~/js/jquery.swipebox.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        /* Basic Gallery */
        $('.swipebox').swipebox();

        /* Video */
        $('.swipebox-video').swipebox();



    });
</script>

Wish.Picture/Wish.Picture.Web/Views/Picture/Upload.cshtml
@{
    ViewData["Title"] = "上传图片";
}
<link type="text/css" href="~/css/fileinput.min.css"/>

<div class="container">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <form class="form-horizontal" asp-controller="Picture" asp-action="UploadImg" method="post" enctype="multipart/form-data">
                <input name="imgFile" type="file" id="imgFile" multiple="" class="file-loading" />
                <div class="form-group">
                    <button type="submit" class="btn btn-default">确认上传</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/js/fileinput.min.js"></script>
<script src="~/js/zh.js"></script>
<script>
    $(function () {
        //0.初始化fileinput
        var oFileInput = new FileInput();
        oFileInput.Init("imgFile", "/Picture/UploadImg");
    });
    var FileInput = function () {
        var oFile = new Object();

        //初始化fileinput控件（第一次初始化）
        oFile.Init = function (ctrlName, uploadUrl) {
            var control = $('#' + ctrlName);

            //初始化上传控件的样式
            control.fileinput({
                language: 'zh', //设置语言
                uploadUrl: uploadUrl, //上传的地址
                allowedFileExtensions: ['jpg', 'gif', 'png'],//接收的文件后缀
                //showUploadedThumbs:false,
                // uploadClass: 'hidden',
                showUpload: false, //是否显示上传按钮
                showCaption: false,//是否显示标题
                browseClass: "btn btn-info", //按钮样式
                dropZoneEnabled: false,//是否显示拖拽区域
                //minImageWidth: 150, //图片的最小宽度
                //minImageHeight: 150,//图片的最小高度
                //maxImageWidth: 150,//图片的最大宽度
                //maxImageHeight: 150,//图片的最大高度
                maxFileSize: 0,//单位为kb，如果为0表示不限制文件大小
                maxFileCount: 5, //表示允许同时上传的最大文件个数
                minFileCount: 1,
                enctype: 'multipart/form-data',
                validateInitialCount: true,
                previewFileIcon: "<i class='glyphicon glyphicon-king'></i>",
                msgFilesTooMany: "选择上传的文件数量({n}) 超过允许的最大数值{m}！",
                fileActionSettings : {
                    showUpload: false,
                    //showRemove: false
                   showZoom:false
                }
            });

            //导入文件上传完成之后的事件
            $("#imgFile").on("fileuploaded", function (event, data, previewId, index) {
                alert(data.response.code);
                // $("#divControl").hide();
            });
        }
        return oFile;
    };
</script>